#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -x

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.ts$') || true

if [ -z "$STAGED_FILES" ]; then
  echo "✅ No TypeScript files staged. Skipping TypeScript check."
  exit 0
fi

echo "🔍 Running TypeScript check on entire project..."
yarn tsc --noEmit

if [ $? -ne 0 ]; then
  echo "❌ TypeScript check failed. Fix errors before committing."
  exit 1
fi

echo "✅ TypeScript check passed. Proceeding with commit."
